### ISSUE TITLE
USB Joystick support

### ISSUE THREAD

**Issue by akanouras** [ghpranav/kernel_tissot#1]
Hello,

I would love to be able to use my USB gamepad with this phone, and surely others have tried it as well.

Please consider merging  https://github.com/ghpranav/android_kernel_xiaomi_msm8953/pull/1/commits/830b782ddcb1aa8426968b9ad4686d90ab5e5e26  into your branches, it should be all that's needed.

Thank you for all your work!

**Comment by ghpranav** [comment]
https://github.com/ghpranav/kernel_tissot/commit/8379fb903979726df5b47e2de268781b17a399fc
